#!/bin/sh

set -e

dkms_name=bcm5974
dkms_version=4.2

case "$1" in
  configure)
    arch=`uname -m`
    kernel=`uname -r`

    if [ -e "/var/lib/dkms/$dkms_name/$dkms_version" ]; then
      echo "Removing old DKMS module $dkms_name/$dkms_version..."
      dkms remove -m $dkms_name -v $dkms_version --all
    fi

    set +e

    # add, compile, and install
    dkms add -m $dkms_name -v $dkms_version
    dkms build -m $dkms_name -v $dkms_version
    dkms install --force $dkms_name/$dkms_version --all
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with an unknown argument: $1"
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
