#!/bin/sh

dkms_name=bcm5974
dkms_version=4.2

set -e

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    moddir="/lib/modules/`uname -r`/kernel/"

    depmod

    if [ -d "/usr/src/$dkms_name-$dkms_version" ]; then
      echo "Removing old module source..."
      set +e

      dkms remove $dkms_name/$dkms_version --all
      rm -fr "/usr/src/$dkms_name-$dkms_version"
    fi
  ;;

  *)
    echo "postrm called with unknown argument: $1"
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
